---
title: Linaro
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/author/:name/"
  company:
    title: Company
    output: true
    permalink: "/:collection/:name/"
  core:
    title: Core
    output: true
    permalink: "/:collection/:path/"
  groups:
    title: Groups
    output: true
    permalink: "/:collection/:path/"
  initiatives:
    title: Initiatives
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  services:
    title: Services
    output: true
    permalink: "/:collection/:name/"
  sig:
    title: Sig
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
- scope:
    path: ''
    type: company
  values:
    layout: container-breadcrumb
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: groups
  values:
    layout: work-layout
- scope:
    path: ''
    type: core
  values:
    layout: work-layout
- scope:
    path: ''
    type: projects
  values:
    layout: work-layout
- scope:
    path: ''
    type: services
  values:
    layout: developer-services
- scope:
    path: ''
    type: initiatives
  values:
    layout: work-layout
- scope:
    path: ''
    type: sig
  values:
    layout: work-layout
- scope:
    path: "/sitemap.xml"
  values:
    redirect_from: "/sitemap/"
- scope:
    path: ''
  values:
    image: "/assets/images/social-media-image.png"
description: 'Linaro is a collaborative engineering organization consolidating and
  optimizing open source software and tools for the ARM architecture.

'
destination: _site
theme: jumbo-jekyll-theme
permalink: "/:categories/:title/"
highlighter: rouge
markdown: kramdown
production: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
safe: false
search-label: Linaro
disqus: true
disqus_shortname: Linaro
url: https://www.linaro.org
liquid:
  error_mode: strict
schema:
  organisation:
    name: Linaro
    url: https://www.linaro.org
    sameAs:
    - https://twitter.com/linaroorg
    - https://www.facebook.com/LinaroOrg
    - https://www.linkedin.com/company/1026961/
    - https://plus.google.com/+LinaroOnAir
    - https://github.com/Linaro
    - https://www.slideshare.net/linaroorg
    address:
      street: Harston Mill, Royston Rd
      town: Harston
      county: Cambridge
      post_code: CB22 7GG
      country_code: UK
exclude:
- Gemfile.lock
- ".gitignore"
- ".git"
- ".asset-cache"
- _site
google-tag-manager: true
social:
  name: Linaro
  links:
  - https://twitter.com/linaroorg
  - https://www.facebook.com/LinaroOrg
  - https://www.linkedin.com/company/1026961/
  - https://plus.google.com/+LinaroOnAir
  - https://github.com/Linaro
  - https://www.slideshare.net/linaroorg
twitter:
  username: linaroorg
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-readme-index
- bootstrap-sass
- uglifier
- jekyll-assets
- jekyll-tidy
- jekyll-redirect-from
- autoprefixer-rails
- jekyll-paginate-v2
jekyll_tidy:
  compress_html: true
  exclude:
  - robots.txt
assets:
  compress:
    js: true
  autoprefixer:
    browsers:
    - last 2 versions
    - "> 5%"
    - IE 9
  sources:
  - assets/js/
  - assets/js/vendor/
  - assets/js/app/
  - assets/images
  - assets/images/members
  - assets/images/people
  - assets/images/content
  - assets/images/blog
  - assets/css/
sass:
  style: compressed
  load_paths:
  - assets/css
pagination:
  permalink: "/:num/"
  enabled: true
  per_page: 10
  trail:
    before: 2
    after: 2
  sort_reverse: true
  sort_field: date
autopages:
  enabled: false
mini_magick:
  blog_thumbnail:
    source: assets/images/blog
    destination: assets/images/thumbnails/blog
    resize: 100x100
    thumbnail: 100x100>
    gravity: Center
    extent: 100x100
  blog_medium:
    source: assets/images/blog
    destination: assets/images/medium/blog
    resize: 300x300
    thumbnail: 300x300>
    gravity: Center
    extent: 300x300
  blog_large:
    source: assets/images/blog
    destination: assets/images/large/blog
    resize: 500x500
    thumbnail: 500x500>
    gravity: Center
    extent: 500x500
  content_thumbnail:
    source: assets/images/content
    destination: assets/images/thumbnails/content
    resize: 100x100
    thumbnail: 100x100>
    gravity: Center
    extent: 100x100
  content_medium:
    source: assets/images/content
    destination: assets/images/medium/content
    resize: 300x300
    thumbnail: 300x300>
    gravity: Center
    extent: 300x300
  content_large:
    source: assets/images/content
    destination: assets/images/large/content
    resize: 500x500
    thumbnail: 500x500>
    gravity: Center
    extent: 500x500
  members_thumbnail:
    source: assets/images/members
    destination: assets/images/thumbnails/members
    resize: 100x100
    thumbnail: 100x100>
    gravity: Center
    extent: 100x100
  members_medium:
    source: assets/images/members
    destination: assets/images/medium/members
    resize: 300x300
    thumbnail: 300x300>
    gravity: Center
    extent: 300x300
  members_large:
    source: assets/images/members
    destination: assets/images/large/members
    resize: 500x500
    thumbnail: 500x500>
    gravity: Center
    extent: 500x500
  people_thumbnail:
    source: assets/images/people
    destination: assets/images/thumbnails/people
    resize: 100x100
    thumbnail: 100x100>
    gravity: Center
    extent: 100x100
  people_medium:
    source: assets/images/people
    destination: assets/images/medium/people
    resize: 300x300
    thumbnail: 300x300>
    gravity: Center
    extent: 300x300
  people_large:
    source: assets/images/people
    destination: assets/images/large/people
    resize: 500x500
    thumbnail: 500x500>
    gravity: Center
    extent: 500x500
using_assets: true
